configured_endpoints: 33
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hubmap-consortium-hubmap-m2%2Fhubmap-entity-sdk-c3a696b58191005fc9480725801b0db9b133dc068c9be9a14ffbab7b2144b2cc.yml
