configured_endpoints: 36
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hubmap-consortium-hubmap-m2%2Fhubmap-entity-sdk-e6e7a8247356aece38780bc89b6b96136b3cd2e4b81abe72be2328d2ac817cac.yml
