configured_endpoints: 36
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hubmap-consortium-hubmap-m2%2Fhubmap-entity-sdk-f501fd04e98c81045180a35c5f031104b97226314d42f85bef9b0cc091bcc0e2.yml
